default:
  image: '$MNPG_BUILD_NODE_IMAGE:14alpine-latest'
  before_script:
    - ./scripts/install_deps.sh
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

stages:
  - release

publish:
  stage: release
  script:
    - npm run release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
